Automatically abort the rebase if it fails
Rebase is used internally to reword the message, but that should largely
be transparent to the user.  If it fails (intentionally or otherwise),
it's nicer to leave the repo clean again at the point it started.

diff --git a/git-reword b/git-reword
--- a/git-reword
+++ b/git-reword
@@ -26,8 +26,13 @@ function main() {
     # Rebase commits starting with our commit of interest (by starting after
     # its parent).  Our sequence editor command will edit the given file in
     # place.  The first line is always the commit we want to reword.
-    GIT_SEQUENCE_EDITOR="perl -pi -e 's/^pick/reword/ if \$. == 1'" \
-        exec git rebase --interactive "$commit^"
+    export GIT_SEQUENCE_EDITOR="perl -pi -e 's/^pick/reword/ if \$. == 1'"
+
+    if ! git rebase --interactive "$commit^"; then
+        echo >&2
+        echo "Reword failed, commit message unchanged." >&2
+        git rebase --abort
+    fi
 }
 
 for arg; do
